### ISSUE TITLE
Consider switching from ghooks to husky

### ISSUE THREAD

**Issue by dtschust** [dtschust/redux-bug-reporter#15]
https://www.npmjs.com/package/husky

**Comment by larsw** [comment]
How is it better than ghooks?

**Comment by larsw** [comment]
By the way, I just found fastlint; https://github.com/mixu/fastlint that will only lint changed files, to speed up the process.

**Comment by dtschust** [comment]
Kent Dodds recommended it on the latest episode of [javascript air](https://javascriptair.com/episodes/2016-08-31/), I like that it looks at existing npm scripts as opposed to requiring a special `ghooks` config in package.json
