### ISSUE TITLE
idea: investigate if it's possible to incorporate html2canvas

### ISSUE THREAD

**Issue by larsw** [dtschust/redux-bug-reporter#17]
Hi,

 Just came across http://html2canvas.hertzen.com/ can render the page to a canvas that can be persisted as an image (e.g. screenshot).

It would be nice to have this feature as a part of the redux-bug-reporter!

**Comment by dtschust** [comment]
Hi Lars! The issue I have with html2canvas is that it isn't a 100% accurate screenshot so it could easily not capture the issue the user is trying to file a bug on. It's definitely non-ideal, but a lot of people use a variety of tools to automatically upload screenshots to a public url like dropbox, and pasting the screenshot URL in is a decent solution in that case. I think the complexity and overhead of adding this library is not worth the limited benefit of storing a not-pixel-perfect screenshot. Thanks for filing the issue though!
