### ISSUE TITLE
The bug container is bigger than it should be and it blocks clicks outside of it's visible area. 

### ISSUE THREAD

**Issue by mehmetg** [dtschust/redux-bug-reporter#4]

**Comment by dtschust** [comment]
Thanks for creating this issue @mehmetg ! Are you seeing the issue when the bug reporter is expanded or collapsed? Also I'm assuming you're seeing this in Desktop Chrome, correct?

**Comment by dtschust** [comment]
I'm able to reproduce, I think my fix is going to be using `pointer-events: none` on the container. Is this gif representative of what you're seeing?
![container interference](https://cloud.githubusercontent.com/assets/210970/17941578/d37b4cf2-69e8-11e6-98fe-39b1be42a819.gif)

**Comment by mehmetg** [comment]
I am seeing this problem in chrome while the tools is collapsed. It was breaking my selenium test and I ended up deleting it from the DOM to run tests. The screenshot below shows the area affected.
![screen shot 2016-08-24 at 2 38 02 pm](https://cloud.githubusercontent.com/assets/1885791/17949084/a9f244e2-6a08-11e6-8c1b-f667fc9c20cd.png)

**Comment by dtschust** [comment]
Ah yes, I see now that the issue is also when collapsed, not just expanded. I've got a working fix but don't have time to push it up today, I'll get something published to npm tomorrow or friday. Thanks for reporting the bug!
