### ISSUE TITLE
Update to standard 8.0.0

### ISSUE THREAD

**Issue by larsw** [dtschust/redux-bug-reporter#9]
Hi,

After I synced my local working copy with your repo, I get the following error when I try to bring my forked github repo up to speed:

  C:\code\redux-bug-reporter\example\index.js:62:24: A space is required before closing bracket
  C:\code\redux-bug-reporter\example\index.js:63:27: A space is required before closing bracket
  C:\code\redux-bug-reporter\example\index.js:65:111: A space is required before closing bracket
  C:\code\redux-bug-reporter\example\index.js:83:92: A space is required before closing bracket
  C:\code\redux-bug-reporter\example\index.js:121:22: A space is required before closing bracket
  C:\code\redux-bug-reporter\example\webpack.example.config.js:8:5: Use path.join() or path.resolve() instead of + to create paths.
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:15:16: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:227:170: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:238:184: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:239:200: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:240:209: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:241:179: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:247:189: A space is required before closing bracket
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:256:5: Expected indentation of 2 space characters but found 4.
  C:\code\redux-bug-reporter\src\redux-bug-reporter.js:258:54: A space is required before closing bracket
  C:\code\redux-bug-reporter\webpack.config.js:7:5: Use path.join() or path.resolve() instead of + to create paths.
  C:\code\redux-bug-reporter\webpack.config.js:8:5: Use path.join() or path.resolve() instead of + to create paths.
  C:\code\redux-bug-reporter\webpack.config.js:11:11: Use path.join() or path.resolve() instead of + to create paths.

**Comment by dtschust** [comment]
Hrm, those seem to be linting errors from a new version of standard than my package requires (5.4.1). Do you know what version of standard is running? Perhaps you have a newer global install that's somehow taking precedence. Does a clean clone work?

**Comment by larsw** [comment]
I ran node_modules\.bin\standard, so it should be the one installed in the project.
I created a PR here https://github.com/dtschust/redux-bug-reporter/pull/10

**Comment by dtschust** [comment]
What does `./node_modules/.bin/standard --version` give you?

**Comment by larsw** [comment]
Bah, 8.0.0 ... weird.

It might be that I ran ncu -u on a temp branch and forgot to clean / reinstall npms. Disregard the PR :-P

**Comment by larsw** [comment]
But, the changes done to the webpack config files are good w.r.t. platform interoperability (path.join).

**Comment by dtschust** [comment]
Agreed, I'll try and migrate to newest version of standard soon and then make these changes. Thanks for playing with the package, I'd love to see how you're using it if you end up using it for anything!

**Comment by larsw** [comment]
Great work, I'm currently investigating a problem that might be related to react-router-redux (and playback). I've also written a small service for submitting bugs, and I was thinking about pulling some of the stuff in redux-bug-reporter.js a bit more apart so it is easier to customize the behavior.

**Comment by dtschust** [comment]
Ah, yeah react-router-redux integration can definitely be problematic, but I was able to get it working on a personal project today with redux-bug-reporter without any weirdness. Good luck!

**Comment by larsw** [comment]
Can you describe what you did to get it working with react-router-redux?

**Comment by dtschust** [comment]
I linked to the code examples above. It's a very simple app with only one route, but during playback the route successfully changes like the filed "bug"
